# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 22:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0017_auto_20180909_0502'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentinstance',
            name='control_data_db_tbl',
        ),
        migrations.RemoveField(
            model_name='equipmentinstance',
            name='control_data_db_url',
        ),
        migrations.RemoveField(
            model_name='equipmentinstance',
            name='data_db_tbl',
        ),
        migrations.RemoveField(
            model_name='equipmentinstance',
            name='data_db_url',
        ),
        migrations.RemoveField(
            model_name='equipmentinstance',
            name='data_fields',
        ),
        migrations.RemoveField(
            model_name='equipmentinstance',
            name='measure_data_db_tbl',
        ),
        migrations.RemoveField(
            model_name='equipmentinstance',
            name='measure_data_db_url',
        ),
    ]
