# Generated by Django 2.1.1 on 2018-11-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0026_auto_20181115_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentdatafield',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Equipment Data Field Name'),
        ),
        migrations.AlterField(
            model_name='equipmentfacility',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Equipment Facility Name'),
        ),
        migrations.AlterField(
            model_name='equipmentinstance',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Equipment Instance Name'),
        ),
        migrations.AlterField(
            model_name='equipmentinstancedatafielddailyagg',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='equipmentsystem',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='equipmentsystem',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=255, verbose_name='Equipment System Name'),
        ),
        migrations.AlterField(
            model_name='equipmentuniquetype',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Equipment Unique Type Name'),
        ),
        migrations.AlterField(
            model_name='equipmentuniquetypegroup',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Equipment Unique Type Group Name'),
        ),
    ]
