# Generated by Django 2.1.5 on 2019-02-15 20:51

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0041_auto_20190215_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentdatafield',
            name='foreign_lang_description',
        ),
        migrations.AlterField(
            model_name='equipmentdatafield',
            name='description',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
