# Generated by Django 2.2.2 on 2019-06-26 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0076_equipmentcomponent_sub_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentcomponent',
            name='directly_interacts_with_components',
            field=models.ManyToManyField(blank=True, related_name='equipment_components_directly_interacts_reverse', related_query_name='equipment_component', to='IoT_DataMgmt.EquipmentComponent'),
        ),
        migrations.AlterField(
            model_name='equipmentcomponent',
            name='sub_components',
            field=models.ManyToManyField(blank=True, related_name='equipment_components_sub_reverse', related_query_name='equipment_component', to='IoT_DataMgmt.EquipmentComponent'),
        ),
    ]
