# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 22:24
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0037_auto_20180831_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentuniquetypegroupdatafieldblueprintbenchmarkmetricprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='equipmentuniquetypegroupdatafieldprofile',
            name='distinct_values',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='equipmentuniquetypegroupdatafieldprofile',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
