# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 01:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0052_auto_20180913_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentinstancedailyriskscore',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
