# Generated by Django 2.1.1 on 2018-11-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0070_auto_20181025_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertdiagnosisstatus',
            name='index',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, unique=True),
        ),
    ]
