# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-10 09:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0002_blueprint_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blueprint',
            options={'ordering': ('url', 'timestamp')},
        ),
        migrations.AddField(
            model_name='blueprint',
            name='timestamp',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
