# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-10 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0007_auto_20180410_0956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blueprint',
            name='equipment_unique_types',
        ),
    ]
