# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0006_auto_20180410_1904'),
        ('IoT_MaintOps', '0010_auto_20180410_1113'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blueprint',
            options={'ordering': ('equipment_general_type', 'equipment_unique_type_group', 'trained_to_date', 'timestamp')},
        ),
        migrations.RemoveField(
            model_name='blueprint',
            name='equipment_unique_type',
        ),
        migrations.AddField(
            model_name='blueprint',
            name='equipment_unique_type_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blueprints', related_query_name='blueprint', to='IoT_DataMgmt.EquipmentUniqueTypeGroup'),
        ),
    ]
