# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-11 05:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0011_auto_20180410_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprint',
            name='equipment_unique_type_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='blueprints', related_query_name='blueprint', to='IoT_DataMgmt.EquipmentUniqueTypeGroup'),
        ),
    ]
