# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 03:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0006_auto_20180410_1904'),
        ('IoT_MaintOps', '0013_auto_20180414_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score_name', models.CharField(max_length=255, unique=True)),
                ('threshold', models.FloatField(default=0)),
                ('from_date', models.DateField(default=None)),
                ('to_date', models.DateField(default=None)),
                ('quantified_risk_degree', models.FloatField(default=0)),
                ('active', models.BooleanField(default=False)),
                ('equipment_general_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', related_query_name='alert', to='IoT_DataMgmt.EquipmentGeneralType')),
                ('equipment_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', related_query_name='alert', to='IoT_DataMgmt.EquipmentInstance')),
                ('equipment_unique_type_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', related_query_name='alert', to='IoT_DataMgmt.EquipmentUniqueTypeGroup')),
            ],
            options={
                'ordering': ('equipment_general_type', 'equipment_unique_type_group', 'equipment_instance', 'risk_score_name', 'threshold', 'from_date', 'to_date', 'quantified_risk_degree', 'active'),
            },
        ),
    ]
