# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0017_auto_20180420_0030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ('equipment_general_type', 'equipment_unique_type_group', 'equipment_instance', 'risk_score_name', 'threshold', 'from_date', 'to_date', 'active')},
        ),
        migrations.AlterModelOptions(
            name='blueprint',
            options={'ordering': ('equipment_general_type', 'equipment_unique_type_group', 'trained_to_date', 'uuid', 'active')},
        ),
    ]
