# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-20 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0018_auto_20180420_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ('risk_score_name', '-threshold', '-quantified_risk_degree')},
        ),
        migrations.AlterModelOptions(
            name='blueprint',
            options={'ordering': ('equipment_general_type', 'equipment_unique_type_group', '-trained_to_date', '-timestamp')},
        ),
    ]
