# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-21 02:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0006_auto_20180410_1904'),
        ('IoT_MaintOps', '0019_auto_20180420_1522'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInstanceProblemDiagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(default=None)),
                ('to_date', models.DateField(default=None)),
                ('equipment_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_problem_instances', related_query_name='equipment_problem_instance', to='IoT_DataMgmt.EquipmentInstance')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentProblemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='equipmentinstanceproblemdiagnosis',
            name='equipment_problem_types',
            field=models.ManyToManyField(blank=True, related_name='equipment_problem_instances', related_query_name='equipment_problem_instance', to='IoT_MaintOps.EquipmentProblemType'),
        ),
    ]
