# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-20 23:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0024_auto_20180712_1029'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertDiagnosisStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveSmallIntegerField(default=0, unique=True)),
                ('name', models.CharField(default=b'to_diagnose', max_length=255, unique=True)),
            ],
            options={
                'ordering': ('index',),
            },
        ),
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ('diagnosis_status', 'risk_score_name', '-threshold', '-quantified_risk_degree')},
        ),
        migrations.RemoveField(
            model_name='alert',
            name='active',
        ),
        migrations.AddField(
            model_name='alert',
            name='diagnosis_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='IoT_MaintOps.AlertDiagnosisStatus'),
        ),
    ]
