# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-22 00:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0027_auto_20180721_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='problems',
        ),
        migrations.RemoveField(
            model_name='equipmentinstanceproblemdiagnosis',
            name='alerts',
        ),
    ]
