# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 05:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0031_alert_equipment_problem_periods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='equipment_problem_periods',
            field=models.ManyToManyField(blank=True, to='IoT_MaintOps.EquipmentInstanceProblemDiagnosis'),
        ),
    ]
