# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 23:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0042_auto_20180904_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoredequipmentdatafieldconfig',
            name='excluded_equipment_data_fields',
            field=models.ManyToManyField(blank=True, related_name='monitored_equipment_data_field_configs_excl', related_query_name='monitored_equipment_data_field_config_excl', to='IoT_DataMgmt.EquipmentDataField'),
        ),
    ]
