# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 00:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0046_auto_20180904_1725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentuniquetypegroupmonitoreddatafieldconfig',
            options={'ordering': ('-active', 'equipment_unique_type_group_service_config', 'monitored_equipment_data_field')},
        ),
        migrations.AddField(
            model_name='equipmentuniquetypegroupmonitoreddatafieldconfig',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
