# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-05 19:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0047_auto_20180904_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentuniquetypegroupdatafieldblueprintbenchmarkmetricprofile',
            name='rmse',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
