# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-08 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0015_equipmentuniquetypegroup_equipment_data_fields'),
        ('IoT_MaintOps', '0048_equipmentuniquetypegroupdatafieldblueprintbenchmarkmetricprofile_rmse'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentuniquetypegroupserviceconfig',
            name='global_excluded_equipment_data_fields',
            field=models.ManyToManyField(blank=True, related_name='equipment_unique_type_group_service_configs', related_query_name='equipment_unique_type_group_service_config', to='IoT_DataMgmt.EquipmentDataField'),
        ),
    ]
