# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0049_equipmentuniquetypegroupserviceconfig_global_excluded_equipment_data_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='alertdiagnosisstatus',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipmentinstanceproblemdiagnosis',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipmentproblemtype',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipmentuniquetypegroupserviceconfig',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
