# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 17:30
from __future__ import unicode_literals

import django.contrib.postgres.fields.ranges
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0053_auto_20180913_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='average_excess_risk_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='alert',
            name='date_range',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='equipmentinstanceproblemdiagnosis',
            name='date_range',
            field=django.contrib.postgres.fields.ranges.DateRangeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentinstanceproblemdiagnosis',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
