# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 21:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0056_auto_20180914_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ('diagnosis_status', '-ongoing', 'risk_score_name', '-threshold', '-cumulative_excess_risk_score')},
        ),
        migrations.AddField(
            model_name='alert',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipmentinstanceproblemdiagnosis',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
