# Generated by Django 2.1.1 on 2018-10-18 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0061_auto_20181016_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='has_associated_equipment_problems',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equipmentinstanceproblemdiagnosis',
            name='has_associated_alerts',
            field=models.BooleanField(default=False),
        ),
    ]
