# Generated by Django 2.1.1 on 2018-10-19 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0063_auto_20181019_2222'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='has_associated_equipment_problems',
            new_name='has_associated_equipment_diagnoses',
        ),
    ]
