# Generated by Django 2.1.5 on 2019-02-01 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0037_auto_20190128_2137'),
        ('IoT_MaintOps', '0079_equipmentuniquetypegroupdatafieldpairwisecorrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentuniquetypegroupmonitoreddatafieldconfig',
            name='auto_included_numeric_equipment_data_fields',
            field=models.ManyToManyField(blank=True, related_name='equipment_unique_type_group_monitored_data_field_configs_auto_incl', related_query_name='equipment_unique_type_group_monitored_data_field_config_auto_incl', to='IoT_DataMgmt.EquipmentDataField'),
        ),
        migrations.AddField(
            model_name='equipmentuniquetypegroupmonitoreddatafieldconfig',
            name='include_categorical_equipment_data_fields',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='equipmentuniquetypegroupmonitoreddatafieldconfig',
            name='manually_included_equipment_data_fields',
            field=models.ManyToManyField(blank=True, related_name='equipment_unique_type_group_monitored_data_field_configs_extra_manual_incl', related_query_name='equipment_unique_type_group_monitored_data_field_config_extra_manual_incl', to='IoT_DataMgmt.EquipmentDataField'),
        ),
    ]
