# Generated by Django 2.1.5 on 2019-02-01 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0082_auto_20190201_0351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentuniquetypegroupmonitoreddatafieldconfig',
            name='include_categorical_equipment_data_fields',
        ),
        migrations.AddField(
            model_name='equipmentuniquetypegroupserviceconfig',
            name='include_categorical_equipment_data_fields',
            field=models.BooleanField(default=True),
        ),
    ]
