# Generated by Django 2.1.5 on 2019-02-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0037_auto_20190128_2137'),
        ('IoT_MaintOps', '0086_auto_20190201_1822'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipmentuniquetypegroupmonitoreddatafieldconfig',
            unique_together={('equipment_unique_type_group_service_config', 'monitored_equipment_data_field')},
        ),
    ]
