# Generated by Django 2.1.5 on 2019-02-10 20:01

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0087_auto_20190207_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True),
        ),
    ]
