# Generated by Django 2.1.5 on 2019-02-23 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0088_alert_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentuniquetypegroupserviceconfig',
            name='equipment_unique_type_group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_unique_type_group_service_configs', related_query_name='equipment_unique_type_group_service_config', to='IoT_DataMgmt.EquipmentUniqueTypeGroup'),
        ),
    ]
