# Generated by Django 2.1.5 on 2019-02-24 01:55

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0055_auto_20190224_0155'),
        ('IoT_MaintOps', '0089_auto_20190223_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprint',
            name='benchmark_metrics',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentinstancedailyriskscore',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='equipmentinstancedailyriskscore',
            name='risk_score_value',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='equipmentinstanceproblemdiagnosis',
            name='from_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='equipmentinstanceproblemdiagnosis',
            name='to_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='equipmentproblemtype',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Equipment Problem Type'),
        ),
        migrations.AlterField(
            model_name='equipmentuniquetypegroupdatafieldblueprintbenchmarkmetricprofile',
            name='n',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='equipmentuniquetypegroupdatafieldblueprintbenchmarkmetricprofile',
            name='trained_to_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='equipmentuniquetypegroupdatafieldprofile',
            name='distinct_values',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentuniquetypegroupdatafieldprofile',
            name='n_distinct_values',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='equipmentuniquetypegroupdatafieldprofile',
            name='valid_proportion',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='equipmentuniquetypegroupserviceconfig',
            name='configs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='equipmentuniquetypegroupdatafieldblueprintbenchmarkmetricprofile',
            unique_together={('equipment_unique_type_group', 'equipment_data_field', 'trained_to_date')},
        ),
        migrations.AlterUniqueTogether(
            name='equipmentuniquetypegroupdatafieldpairwisecorrelation',
            unique_together={('equipment_unique_type_group', 'equipment_data_field', 'equipment_data_field_2')},
        ),
        migrations.AlterUniqueTogether(
            name='equipmentuniquetypegroupdatafieldprofile',
            unique_together={('equipment_unique_type_group', 'equipment_data_field', 'to_date')},
        ),
    ]
