# Generated by Django 2.2.1 on 2019-05-14 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0099_auto_20190514_0406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentuniquetypegroupdatafieldpairwisecorrelation',
            options={'ordering': ('equipment_unique_type_group', 'equipment_data_field', 'equipment_data_field_2')},
        ),
    ]
