# Generated by Django 2.2.1 on 2019-05-17 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0104_auto_20190516_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentinstancealarmperiod',
            options={'ordering': ('equipment_instance', '-from_utc_date_time')},
        ),
    ]
