# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-17 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0007_auto_20180703_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInstanceAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('date', models.DateField()),
                ('equipment_instances', models.ManyToManyField(blank=True, related_name='equipment_instance_associations', related_query_name='equipment_instance_association', to='IoT_DataMgmt.EquipmentInstance')),
            ],
            options={
                'ordering': ('name', 'date'),
            },
        ),
    ]
