# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-08 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0014_auto_20180803_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentuniquetypegroup',
            name='equipment_data_fields',
            field=models.ManyToManyField(blank=True, related_name='equipment_unique_type_groups', related_query_name='equipment_unique_type_group', to='IoT_DataMgmt.EquipmentDataField'),
        ),
    ]
