# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-02 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0018_auto_20180926_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentuniquetypegroup',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
