# Generated by Django 2.1.1 on 2018-10-16 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0019_auto_20181002_1415'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentdatafield',
            name='nullable',
        ),
    ]
