# Generated by Django 2.1.1 on 2018-11-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0025_auto_20181110_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Data Type Name'),
        ),
        migrations.AlterField(
            model_name='equipmentdatafieldtype',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Equipment Data Field Type Name'),
        ),
        migrations.AlterField(
            model_name='equipmentgeneraltype',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Equipment General Type Name'),
        ),
        migrations.AlterField(
            model_name='numericmeasurementunit',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Numeric Measurement Unit Name'),
        ),
    ]
