# Generated by Django 2.1.4 on 2019-01-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0032_globalconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalconfig',
            name='key',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
