# Generated by Django 2.1.5 on 2019-01-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0033_auto_20190107_0455'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentdatafield',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='equipmentdatafield',
            name='foreign_lang_description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
