# Generated by Django 2.1.5 on 2019-02-15 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0038_equipmentfacility_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentuniquetype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentuniquetype',
            name='foreign_lang_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentuniquetypegroup',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
