# Generated by Django 2.1.5 on 2019-02-15 19:02

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0039_auto_20190215_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='numericmeasurementunit',
            name='description',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
