# Generated by Django 2.1.5 on 2019-02-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0048_equipmentinstancedailymetadata_n_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentinstancedailymetadata',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
