# Generated by Django 2.2.1 on 2019-05-16 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0070_auto_20190516_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentinstancedailymetadata',
            options={'verbose_name_plural': 'Equipment Instance Daily Metadata'},
        ),
    ]
