# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-10 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprint',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
