# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-10 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0004_auto_20180410_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprint',
            name='uuid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
