# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-12 04:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0021_remove_blueprint_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinstanceproblemdiagnosis',
            name='comments',
            field=models.TextField(null=True),
        ),
    ]
