# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-23 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0029_equipmentproblemperiod_alerts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentinstanceproblemdiagnosis',
            name='alerts',
            field=models.ManyToManyField(blank=True, related_name='equipment_problem_instances', related_query_name='equipment_problem_instance', to='IoT_MaintOps.Alert'),
        ),
    ]
