# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 20:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0033_auto_20180831_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentuniquetypegroupmeasurementdatafieldprofile',
            name='distinct_values',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='equipmentuniquetypegroupmeasurementdatafieldprofile',
            name='n_distinct_values',
            field=models.IntegerField(default=0),
        ),
    ]
