# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-31 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0038_auto_20180831_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentuniquetypegroupdatafieldprofile',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
