# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0014_auto_20180803_1031'),
        ('IoT_MaintOps', '0039_auto_20180831_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoredEquipmentDataFieldConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('excluded_equipment_data_fields', models.ManyToManyField(related_name='monitored_equipment_data_field_configs', related_query_name='monitored_equipment_data_field_config', to='IoT_DataMgmt.EquipmentDataField')),
                ('monitored_equipment_data_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='monitored_equipment_data_field_configs', related_query_name='monitored_equipment_data_field_config', to='IoT_DataMgmt.EquipmentDataField')),
            ],
        ),
        migrations.AddField(
            model_name='equipmentuniquetypegroupserviceconfig',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentuniquetypegroupserviceconfig',
            name='monitored_equipment_data_field_configs',
            field=models.ManyToManyField(related_name='equipment_unique_type_group_service_configs', related_query_name='equipment_unique_type_group_service_config', to='IoT_MaintOps.MonitoredEquipmentDataFieldConfig'),
        ),
    ]
