# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 22:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0041_auto_20180904_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitoredequipmentdatafieldconfig',
            name='excluded_equipment_data_fields',
            field=models.ManyToManyField(blank=True, related_name='monitored_equipment_data_field_configs', related_query_name='monitored_equipment_data_field_config', to='IoT_DataMgmt.EquipmentDataField'),
        ),
    ]
