# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-13 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0017_auto_20180909_0502'),
        ('IoT_MaintOps', '0050_auto_20180909_0502'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInstanceDailyRiskScore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_score_name', models.CharField(max_length=255, unique=True)),
                ('date', models.DateField(default=None)),
                ('risk_score_value', models.FloatField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('equipment_general_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', related_query_name='alert', to='IoT_DataMgmt.EquipmentGeneralType')),
                ('equipment_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', related_query_name='alert', to='IoT_DataMgmt.EquipmentInstance')),
                ('equipment_unique_type_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alerts', related_query_name='alert', to='IoT_DataMgmt.EquipmentUniqueTypeGroup')),
            ],
            options={
                'ordering': ('equipment_general_type', 'equipment_unique_type_group', 'equipment_instance', 'risk_score_name', '-date'),
            },
        ),
    ]
