# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0059_alert_last_risk_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprint',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
