# Generated by Django 2.1.1 on 2018-10-20 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0065_auto_20181019_2348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='equipment_diagnoses',
            new_name='equipment_problem_diagnoses',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='has_associated_equipment_diagnoses',
            new_name='has_associated_equipment_problem_diagnoses',
        ),
        migrations.AlterField(
            model_name='equipmentinstanceproblemdiagnosis',
            name='equipment_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_problem_diagnoses', related_query_name='equipment_problem_diagnosis', to='IoT_DataMgmt.EquipmentInstance'),
        ),
        migrations.AlterField(
            model_name='equipmentinstanceproblemdiagnosis',
            name='equipment_problem_types',
            field=models.ManyToManyField(blank=True, related_name='equipment_problem_diagnoses', related_query_name='equipment_problem_diagnosis', to='IoT_MaintOps.EquipmentProblemType'),
        ),
    ]
