# Generated by Django 2.1.1 on 2018-10-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0069_auto_20181024_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertdiagnosisstatus',
            name='name',
            field=models.CharField(default='to_diagnose', max_length=255, unique=True, verbose_name='Alert Diagnosis Status Name'),
        ),
        migrations.AlterField(
            model_name='equipmentproblemtype',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Equipment Problem Type Name'),
        ),
    ]
