# Generated by Django 2.1.3 on 2018-12-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0075_globalconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentuniquetypegroupserviceconfig',
            name='from_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentuniquetypegroupserviceconfig',
            name='to_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
