# Generated by Django 2.1.5 on 2019-02-24 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0055_auto_20190224_0155'),
        ('IoT_MaintOps', '0090_auto_20190224_0155'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipmentinstancedailyriskscore',
            unique_together={('equipment_unique_type_group', 'equipment_instance', 'risk_score_name', 'date')},
        ),
    ]
