# Generated by Django 2.2.1 on 2019-05-13 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0093_auto_20190224_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentinstanceproblemdiagnosis',
            name='equipment_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_instance_problem_diagnoses', related_query_name='equipment_instance_problem_diagnosis', to='IoT_DataMgmt.EquipmentInstance'),
        ),
        migrations.AlterField(
            model_name='equipmentinstanceproblemdiagnosis',
            name='equipment_problem_types',
            field=models.ManyToManyField(blank=True, related_name='equipment_instance_problem_diagnoses', related_query_name='equipment_instance_problem_diagnosis', to='IoT_MaintOps.EquipmentProblemType'),
        ),
    ]
