# Generated by Django 2.2.1 on 2019-05-16 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0103_auto_20190516_2225'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertdiagnosisstatus',
            options={'ordering': ('index',), 'verbose_name_plural': 'Alert Diagnosis Statuses'},
        ),
    ]
