# Generated by Django 3.1.1 on 2020-09-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0111_auto_20191003_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='info',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='blueprint',
            name='benchmark_metrics',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentuniquetypegroupdatafieldprofile',
            name='distinct_values',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentuniquetypegroupmonitoreddatafieldconfig',
            name='auto_included_numeric_equipment_data_fields',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentuniquetypegroupmonitoreddatafieldconfig',
            name='highly_correlated_numeric_equipment_data_fields',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentuniquetypegroupmonitoreddatafieldconfig',
            name='lowly_correlated_numeric_equipment_data_fields',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentuniquetypegroupserviceconfig',
            name='configs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
