# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-03 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0002_equipmentuniquetype_data_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('data_fields', models.ManyToManyField(blank=True, related_name='equipment_instances', related_query_name='equipment_instance', to='IoT_DataMgmt.EquipmentDataField')),
                ('equipment_general_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_instances', related_query_name='equipment_instance', to='IoT_DataMgmt.EquipmentGeneralType')),
                ('equipment_unique_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_instances', related_query_name='equipment_instance', to='IoT_DataMgmt.EquipmentUniqueType')),
            ],
            options={
                'ordering': ('equipment_general_type', 'equipment_unique_type', 'name'),
            },
        ),
    ]
