# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-03 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0004_auto_20180103_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentdatafield',
            name='nullable',
            field=models.BooleanField(default=True),
        ),
    ]
