# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-06 23:37
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0021_auto_20181025_0733'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInstanceDataFieldDailyAggregate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('daily_count', models.IntegerField(default=0)),
                ('daily_distinct_value_counts', django.contrib.postgres.fields.jsonb.JSONField(default=dict)),
                ('daily_min', models.FloatField(blank=True, null=True)),
                ('daily_quartile', models.FloatField(blank=True, null=True)),
                ('daily_median', models.FloatField(blank=True, null=True)),
                ('daily_mean', models.FloatField(blank=True, null=True)),
                ('daily_3rd_quartile', models.FloatField(blank=True, null=True)),
                ('daily_max', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('equipment_data_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_instance_data_field_daily_aggregates', related_query_name='equipment_instance_data_field_daily_aggregate', to='IoT_DataMgmt.EquipmentDataField')),
                ('equipment_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_instance_data_field_daily_aggregates', related_query_name='equipment_instance_data_field_daily_aggregate', to='IoT_DataMgmt.EquipmentInstance')),
            ],
            options={
                'ordering': ('equipment_instance', 'equipment_data_field', 'date'),
            },
        ),
    ]
