# Generated by Django 2.2.1 on 2019-05-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0068_auto_20190514_0337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentinstancedailymetadata',
            options={},
        ),
    ]
