# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-14 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0054_auto_20180914_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'ordering': ('diagnosis_status', 'risk_score_name', '-threshold', '-cumulative_excess_risk_score')},
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='quantified_risk_degree',
            new_name='cumulative_excess_risk_score',
        ),
    ]
