# Generated by Django 2.1.1 on 2018-10-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0067_equipmentproblemperiod_has_equipment_problems'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentinstanceproblemdiagnosis',
            options={'ordering': ('-ongoing', '-from_date', '-to_date', 'equipment_instance', 'dismissed')},
        ),
    ]
