# Generated by Django 2.2.1 on 2019-05-23 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0106_remove_globalconfig_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertdiagnosisstatus',
            name='last_updated',
        ),
    ]
