# Generated by Django 2.2.1 on 2019-05-23 02:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0074_auto_20190522_1956'),
        ('IoT_MaintOps', '0107_remove_alertdiagnosisstatus_last_updated'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipmentinstancealarmperiod',
            unique_together={('equipment_instance', 'alarm_type', 'from_utc_date_time')},
        ),
        migrations.AlterUniqueTogether(
            name='equipmentinstanceproblemdiagnosis',
            unique_together={('equipment_instance', 'from_date')},
        ),
    ]
