# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-03 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0006_auto_20180410_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentdatafield',
            name='lower_numeric_null',
            field=models.FloatField(default=-1073741824),
        ),
        migrations.AlterField(
            model_name='equipmentdatafield',
            name='upper_numeric_null',
            field=models.FloatField(default=1073741824),
        ),
    ]
