# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-25 03:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0008_equipmentinstanceassociation'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumericMeasurementUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='equipmentdatafield',
            name='numeric_measurement_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_data_fields', related_query_name='equipment_data_field', to='IoT_DataMgmt.NumericMeasurementUnit'),
        ),
    ]
