# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-03 07:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0009_auto_20180724_2039'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='equipmentinstance',
            name='equipment_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_instances', related_query_name='equipment_instance', to='IoT_DataMgmt.EquipmentFacility'),
        ),
        migrations.AddField(
            model_name='equipmentinstanceassociation',
            name='equipment_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_instance_associations', related_query_name='equipment_instance_association', to='IoT_DataMgmt.EquipmentFacility'),
        ),
    ]
