# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-03 17:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0013_auto_20180803_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentsystem',
            name='equipment_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_systems', related_query_name='equipment_system', to='IoT_DataMgmt.EquipmentFacility'),
        ),
        migrations.AlterField(
            model_name='equipmentsystem',
            name='equipment_instances',
            field=models.ManyToManyField(blank=True, related_name='equipment_systems', related_query_name='equipment_system', to='IoT_DataMgmt.EquipmentInstance'),
        ),
    ]
