# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-08 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0015_equipmentuniquetypegroup_equipment_data_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentinstance',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
