# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-09 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0016_auto_20180908_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentdatafield',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipmentfacility',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipmentgeneraltype',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipmentinstance',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipmentsystem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipmentuniquetype',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='equipmentuniquetypegroup',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='numericmeasurementunit',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
