# Generated by Django 2.1.1 on 2018-11-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0023_auto_20181110_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinstancedatafielddailyagg',
            name='daily_ourlier_rst_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipmentinstancedatafielddailyagg',
            name='daily_ourlier_rst_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
