# Generated by Django 2.1.1 on 2018-11-10 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0024_auto_20181110_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentinstancedatafielddailyagg',
            old_name='daily_ourlier_rst_max',
            new_name='daily_outlier_rst_max',
        ),
        migrations.RenameField(
            model_name='equipmentinstancedatafielddailyagg',
            old_name='daily_ourlier_rst_min',
            new_name='daily_outlier_rst_min',
        ),
    ]
