# Generated by Django 2.1.1 on 2018-11-21 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0027_auto_20181115_0423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentinstancedatafielddailyagg',
            options={'ordering': ()},
        ),
    ]
