# Generated by Django 2.1.3 on 2018-11-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0029_auto_20181121_0053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='numericmeasurementunit',
            name='last_updated',
        ),
    ]
