# Generated by Django 2.1.3 on 2018-11-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0030_remove_numericmeasurementunit_last_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentgeneraltype',
            name='last_updated',
        ),
    ]
