# Generated by Django 2.1.5 on 2019-01-26 18:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0034_auto_20190126_1711'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentinstance',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
