# Generated by Django 2.1.5 on 2019-01-26 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0035_equipmentinstance_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipmentinstance',
            name='control_data_file_url',
        ),
        migrations.RemoveField(
            model_name='equipmentinstance',
            name='data_file_url',
        ),
        migrations.RemoveField(
            model_name='equipmentinstance',
            name='measure_data_file_url',
        ),
    ]
