# Generated by Django 2.1.5 on 2019-02-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0042_auto_20190215_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentuniquetype',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Equipment Unique Type Name'),
        ),
    ]
