# Generated by Django 2.1.5 on 2019-02-20 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0043_auto_20190219_0135'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipmentdatafield',
            unique_together={('equipment_general_type', 'name')},
        ),
    ]
