# Generated by Django 2.1.5 on 2019-02-22 23:58

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0044_auto_20190220_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInstanceDailyMetadata',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(db_index=True)),
                ('schema', django.contrib.postgres.fields.jsonb.JSONField(default=None)),
                ('n_rows', models.IntegerField(default=0)),
                ('equipment_instance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_instance_daily_metadata', related_query_name='equipment_instance_daily_metadata', to='IoT_DataMgmt.EquipmentInstance')),
            ],
            options={
                'ordering': ('equipment_instance', 'date'),
            },
        ),
    ]
