# Generated by Django 2.1.5 on 2019-02-23 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0050_auto_20190223_0551'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipmentinstancedailymetadata',
            unique_together={('equipment_instance', 'date')},
        ),
    ]
