# Generated by Django 2.1.5 on 2019-02-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0051_auto_20190223_0644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentinstancedailymetadata',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
