# Generated by Django 2.1.5 on 2019-02-23 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0052_auto_20190223_0655'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='equipmentinstancedatafielddailyagg',
            unique_together={('equipment_instance', 'equipment_data_field', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='equipmentsystem',
            unique_together={('name', 'date')},
        ),
    ]
