# Generated by Django 2.1.5 on 2019-02-23 23:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0053_auto_20190223_0816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentdatafield',
            options={'ordering': ('equipment_general_type', 'name')},
        ),
        migrations.AlterField(
            model_name='datatype',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Data Type'),
        ),
        migrations.AlterField(
            model_name='equipmentdatafield',
            name='name',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Equipment Data Field'),
        ),
        migrations.AlterField(
            model_name='equipmentdatafieldtype',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Equipment Data Field Type'),
        ),
        migrations.AlterField(
            model_name='equipmentfacility',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Equipment Facility'),
        ),
        migrations.AlterField(
            model_name='equipmentgeneraltype',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Equipment General Type'),
        ),
        migrations.AlterField(
            model_name='equipmentinstance',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Equipment Instance'),
        ),
        migrations.AlterField(
            model_name='equipmentinstancedailymetadata',
            name='n_columns',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='equipmentinstancedailymetadata',
            name='n_rows',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='equipmentinstancedailymetadata',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
        migrations.AlterField(
            model_name='equipmentinstancedatafielddailyagg',
            name='daily_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='equipmentinstancedatafielddailyagg',
            name='daily_distinct_value_counts',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentuniquetype',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Equipment Unique Type'),
        ),
        migrations.AlterField(
            model_name='equipmentuniquetypegroup',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Equipment Unique Type Group'),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='value',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='numericmeasurementunit',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Numeric Measurement Unit'),
        ),
    ]
