# Generated by Django 2.1.5 on 2019-02-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0054_auto_20190223_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentsystem',
            name='name',
            field=models.CharField(db_index=True, default=None, max_length=255, verbose_name='Equipment System'),
        ),
    ]
