# Generated by Django 2.2.1 on 2019-05-09 21:18

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0057_auto_20190322_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True, verbose_name='Equipment Component')),
                ('description', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('equipment_data_fields', models.ManyToManyField(blank=True, related_name='equipment_components', related_query_name='equipment_component', to='IoT_DataMgmt.EquipmentDataField')),
                ('equipment_general_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_components', related_query_name='equipment_component', to='IoT_DataMgmt.EquipmentGeneralType')),
                ('equipment_unique_types', models.ManyToManyField(blank=True, related_name='equipment_components', related_query_name='equipment_component', to='IoT_DataMgmt.EquipmentUniqueType')),
            ],
            options={
                'ordering': ('equipment_general_type', 'name'),
                'unique_together': {('equipment_general_type', 'name')},
            },
        ),
        migrations.AddField(
            model_name='equipmentdatafield',
            name='components',
            field=models.ManyToManyField(blank=True, to='IoT_DataMgmt.EquipmentComponent'),
        ),
    ]
