# Generated by Django 2.2.1 on 2019-05-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0061_auto_20190509_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentcomponent',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
