# Generated by Django 2.2.1 on 2019-05-14 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0064_auto_20190514_0331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentdatafield',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='equipment_data_fields_reverse', related_query_name='equipment_data_field', to='IoT_DataMgmt.EquipmentComponent'),
        ),
        migrations.AlterField(
            model_name='equipmentuniquetype',
            name='components',
            field=models.ManyToManyField(blank=True, related_name='equipment_unique_types_reverse', related_query_name='equipment_unique_type', to='IoT_DataMgmt.EquipmentComponent'),
        ),
        migrations.AlterField(
            model_name='equipmentuniquetype',
            name='data_fields',
            field=models.ManyToManyField(blank=True, related_name='equipment_unique_types_reverse', related_query_name='equipment_unique_type', to='IoT_DataMgmt.EquipmentDataField'),
        ),
        migrations.AlterField(
            model_name='equipmentuniquetype',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='equipment_unique_types_reverse', related_query_name='equipment_unique_type', to='IoT_DataMgmt.EquipmentUniqueTypeGroup'),
        ),
    ]
