# Generated by Django 2.2.1 on 2019-05-14 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0067_auto_20190514_0335'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentuniquetype',
            old_name='groups',
            new_name='equipment_unique_type_groups',
        ),
    ]
