# Generated by Django 2.2.1 on 2019-05-21 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0072_remove_globalconfig_last_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentfacility',
            options={'ordering': ('name',), 'verbose_name_plural': 'Equipment Facilities'},
        ),
    ]
