# Generated by Django 2.2.1 on 2019-05-22 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0073_auto_20190521_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentsystem',
            options={'ordering': ('equipment_facility', 'name', 'date')},
        ),
    ]
