# Generated by Django 3.1.1 on 2020-09-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0081_auto_20191019_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentcomponent',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentdatafield',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentfacility',
            name='info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentinstance',
            name='info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentinstancedatafielddailyagg',
            name='daily_distinct_value_counts',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentuniquetype',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentuniquetypegroup',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='globalconfig',
            name='value',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='numericmeasurementunit',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
