# Generated by Django 2.2.1 on 2019-05-09 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0060_equipmentdatafield_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentuniquetype',
            name='components',
            field=models.ManyToManyField(blank=True, to='IoT_DataMgmt.EquipmentComponent'),
        ),
        migrations.AddField(
            model_name='equipmentuniquetypegroup',
            name='equipment_components',
            field=models.ManyToManyField(blank=True, related_name='equipment_unique_type_groups', related_query_name='equipment_unique_type_group', to='IoT_DataMgmt.EquipmentComponent'),
        ),
    ]
