# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-10 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_DataMgmt', '0005_auto_20180103_1059'),
        ('IoT_MaintOps', '0005_auto_20180410_0337'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blueprint',
            options={'ordering': ('equipment_general_type', 'uuid', 'timestamp')},
        ),
        migrations.AddField(
            model_name='blueprint',
            name='equipment_general_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='blueprints', related_query_name='blueprint', to='IoT_DataMgmt.EquipmentGeneralType'),
        ),
        migrations.AddField(
            model_name='blueprint',
            name='equipment_unique_types',
            field=models.ManyToManyField(blank=True, related_name='blueprints', related_query_name='blueprint', to='IoT_DataMgmt.EquipmentUniqueType'),
        ),
    ]
