# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-16 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IoT_MaintOps', '0057_auto_20180914_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentuniquetypegroupdatafieldblueprintbenchmarkmetricprofile',
            name='n',
            field=models.BigIntegerField(default=0),
        ),
    ]
